version: '2'
services:
  webservice1:
    container_name: site1
    image: nginx:stable
    volumes:
      - ./webservice1:/usr/share/nginx/html/
    expose:
      - "80"

  apiservice1:
    container_name: api1
    build:
      context: ./apiservice1
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - 8080:8080

  webservice2:
    container_name: site2
    image: nginx:stable
    volumes:
      - ./webservice2:/usr/share/nginx/html/
    expose:
      - "80"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
